/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1.app;



import lab1.io.ConsoleInputManager;
import lab1.io.ConsoleOutputManager;
import lab1.io.InputManager;
import lab1.io.OutputManager;
import lab1.logic.LinearSystem;
import lab1.logic.Matrix;
import lab1.logic.Solver;
import lombok.Getter;
import lombok.Setter;

public class App {
    static private App instanse;
    public static App getInstanse() {
        if(instanse == null) {
            instanse = new App();
        }
        return instanse;
    }
    

    @Getter @Setter
    private InputManager in;
    @Getter 
    private OutputManager out;

    @Getter @Setter
    private boolean running;
    @Getter 
    private Solver solver;
    private App() {
        out = new ConsoleOutputManager();
        in = new ConsoleInputManager();
        solver = new Solver();
    }

    public void printGreetings() {
        /* Print Black Text on Red background */
        
        out.print("\n█▀▀ █░░█ █▀▀ ▀▀█▀▀ █▀▀ █▀▄▀█   █▀▀█ █▀▀   █░░ ░▀░ █▀▀▄ █▀▀ █▀▀█ █▀▀█ \n▀▀█ █▄▄█ ▀▀█ ░░█░░ █▀▀ █░▀░█   █░░█ █▀▀   █░░ ▀█▀ █░░█ █▀▀ █▄▄█ █▄▄▀ \n▀▀▀ ▄▄▄█ ▀▀▀ ░░▀░░ ▀▀▀ ▀░░░▀   ▀▀▀▀ ▀░░   ▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀ ▀░░▀ ▀░▀▀ \n\n█▀▀ █▀▀█ █░░█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀█ █▀▀▄ █▀▀   █░█ ░▀░ █░░ █░░ █▀▀ █▀▀█ \n█▀▀ █░░█ █░░█ █▄▄█ ░░█░░ ▀█▀ █░░█ █░░█ ▀▀█   █▀▄ ▀█▀ █░░ █░░ █▀▀ █▄▄▀ \n▀▀▀ ▀▀▀█ ░▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀   ▀░▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░▀▀");
        out.print("\t \t \t \t \t \t \tby @dimka_228");
        out.print("\n\n\n");
        
        
    }

    void test(){
        LinearSystem system = LinearSystem.of(3, new double[]{
            1,2,1,8,
            2,1,2,10,
            3,3,1,12
        } );
        //system.solve();

        system.print();
        solver.setSystem(system);
        solver.solve();
        out.print("\nПуть решения: \n\n" + solver.getSolutionWay() + "\n");
        out.print("\nРешение системы имеет вид: \n\n" + solver.getSolution() + "\n");
    }
    public void start(){
       
        
        setRunning(true);
        printGreetings();
        test();
        while (running) {
            run();
        }
        //solver.readFromConsole();


        /*solver.solve();

        solver.getSolution().print();*/
    }
    void printSolution(){
        solver.getSystem().print();
        solver.solve();
        out.print("\nПуть решения: \n\n" + solver.getSolutionWay() + "\n");
        out.print("\nРешение системы имеет вид: \n\n" + solver.getSolution() + "\n");
    }

    public void run(){
        int cmd = in.readCommand();
        Solver solver =  new Solver();
        if(cmd == 3) {
            stop();
            return;
        }
        if(cmd == 1) {
            solver.readFromConsole();
            printSolution();
            
        }
        else if(cmd == 2) {
            String path = in.readPath();
            try {
                solver.readFromFile(path);
                printSolution();
            } catch (Exception e) {
                out.print("Ошибка при чтении файла: " + e.getMessage());
            }
        }
        
   
        
    }

    public void stop(){
        running = false;
    }


    public void exit(){
        System.exit(0);
    }


    
}
