/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1.app;



import java.io.FileNotFoundException;
import java.io.IOException;

import lab1.io.ConsoleInputManager;
import lab1.io.ConsoleOutputManager;
import lab1.io.FileInputManager;
import lab1.io.InputManager;
import lab1.io.OutputManager;
import lab1.logic.LinearSystem;
import lab1.logic.Matrix;
import lab1.logic.Solver;
import lombok.Getter;
import lombok.Setter;

public class App {
    static private App instanse;
    public static App getInstanse() {
        if(instanse == null) {
            instanse = new App();
        }
        return instanse;
    }
    

    @Getter @Setter
    private InputManager in;
    @Getter 
    private OutputManager out;

    @Getter @Setter
    private boolean running;
    @Getter 
    private Solver solver;
    private App() {
        out = new ConsoleOutputManager();
        in = new ConsoleInputManager();
        solver = new Solver();
    }

    public void printGreetings() {
        /* Print Black Text on Red background */
        
        out.print("\n█▀▀ █░░█ █▀▀ ▀▀█▀▀ █▀▀ █▀▄▀█   █▀▀█ █▀▀   █░░ ░▀░ █▀▀▄ █▀▀ █▀▀█ █▀▀█ \n▀▀█ █▄▄█ ▀▀█ ░░█░░ █▀▀ █░▀░█   █░░█ █▀▀   █░░ ▀█▀ █░░█ █▀▀ █▄▄█ █▄▄▀ \n▀▀▀ ▄▄▄█ ▀▀▀ ░░▀░░ ▀▀▀ ▀░░░▀   ▀▀▀▀ ▀░░   ▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀ ▀░░▀ ▀░▀▀ \n\n█▀▀ █▀▀█ █░░█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀█ █▀▀▄ █▀▀   █░█ ░▀░ █░░ █░░ █▀▀ █▀▀█ \n█▀▀ █░░█ █░░█ █▄▄█ ░░█░░ ▀█▀ █░░█ █░░█ ▀▀█   █▀▄ ▀█▀ █░░ █░░ █▀▀ █▄▄▀ \n▀▀▀ ▀▀▀█ ░▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀   ▀░▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░▀▀");
        out.print("\t \t \t \t \t \t \tby @dimka_228");
        out.print("\n\n\n");
        
        
    }

    void test(){
        LinearSystem system = LinearSystem.of(3, 
            1,2,1,8,
            2,1,2,10,
            3,3,1,12
        );
        //system.solve();

        
        solver.setSystem(system);
        printSolution();
    }
    public void start(){
       
        
        setRunning(true);
        printGreetings();
        test();
        while (running) {
            run();
        }
  
    }
    void printSolution(){
        
        out.print("Исходная истема имеет вид: \n" + solver.getSystem() + "\n");
        out.print("Детерминант: " + solver.getSystem().getCoefficients().getDeterminant() + "\n");
        solver.solve();
        //out.print(solver.getSolutionWay().getDescription());
        out.print("Треугольная матрица: \n" + solver.getSystem() + "\n");
        //out.print("\nПуть решения: \n\n" + solver.getSolutionWay() + "\n");

        out.print("Решение системы имеет вид: \n" + solver.getSolution() + "\n");
        out.print("Вектор невязок: \n" + solver.getErrors() + "\n");
    }

    public void run(){
        int cmd = in.readCommand();
      
        if(cmd == 3) {
            stop();
            return;
        }
        if(cmd == 1) {
            LinearSystem system = in.readLinearSystem();
            solver.setSystem(system);
            printSolution();
            
        }
        else if(cmd == 2) {
            String path = in.readPath();
            try (InputManager fileInput = new FileInputManager(path)){
                LinearSystem system = fileInput.readLinearSystem();
                solver.setSystem(system);
                printSolution();
            } catch(FileNotFoundException e) {
                out.print("Файл "+ path + " не найден");
            } catch (IOException e) {
                out.print("Ошибка при чтении файла " + path);
            }
            catch (IllegalArgumentException e) {
                out.print("Данные в файле некорректны: " + path);
            }
            catch (Exception e) {
                out.print("Неизвестная ошибка");
            }

        }
        
   
        
    }

    public void stop(){
        running = false;
    }


    public void exit(){
        System.exit(0);
    }


    
}
