/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;



import lab1.io.ConsoleManager;
import lab1.io.IOManager;
import lab1.logic.LinearSystem;
import lab1.logic.Matrix;
import lab1.logic.Solver;
import lombok.Getter;
import lombok.Setter;

public class App {
    static private App instanse;
    public static App getInstanse() {
        if(instanse == null) {
            instanse = new App();
        }
        return instanse;
    }

    @Getter @Setter
    private IOManager ioManager;

    private App() {
        ioManager = new ConsoleManager();
    }

    public void printGreetings() {
        /* Print Black Text on Red background */
        
        ioManager.print("\n█▀▀ █░░█ █▀▀ ▀▀█▀▀ █▀▀ █▀▄▀█   █▀▀█ █▀▀   █░░ ░▀░ █▀▀▄ █▀▀ █▀▀█ █▀▀█ \n▀▀█ █▄▄█ ▀▀█ ░░█░░ █▀▀ █░▀░█   █░░█ █▀▀   █░░ ▀█▀ █░░█ █▀▀ █▄▄█ █▄▄▀ \n▀▀▀ ▄▄▄█ ▀▀▀ ░░▀░░ ▀▀▀ ▀░░░▀   ▀▀▀▀ ▀░░   ▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀ ▀░░▀ ▀░▀▀ \n\n█▀▀ █▀▀█ █░░█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀█ █▀▀▄ █▀▀   █░█ ░▀░ █░░ █░░ █▀▀ █▀▀█ \n█▀▀ █░░█ █░░█ █▄▄█ ░░█░░ ▀█▀ █░░█ █░░█ ▀▀█   █▀▄ ▀█▀ █░░ █░░ █▀▀ █▄▄▀ \n▀▀▀ ▀▀▀█ ░▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀   ▀░▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░▀▀");
        ioManager.print("\t \t \t \t \t \t \tby @dimka_228");
         ioManager.print("\n\n\n");
        
        
    }

    public void start(){
        Matrix matrix = new Matrix(3);
        matrix.setElement(0, 0, 1);
        matrix.setName("A");
        
        Solver solver = new Solver();
        //solver.readFromConsole();


        LinearSystem system = LinearSystem.of(3, new double[]{
            1,2,1,8,
            2,1,2,10,
            3,3,1,12
        } );
        //system.solve();

        system.print();
        system.solve();
        system.printSolution();
    }


    
}
